name: memo_capture
description: "Memo Capture is a memo app for those who value their memories and want a simple, intuitive way to organize and relive them. Whether you're capturing daily moments, special occasions, or important notes, this app helps you store and manage everything efficiently. With features like easy-to-use tagging, customizable albums, and secure cloud backups, memo_capture ensures your memories are safe and easily accessible anytime, anywhere. Plus, it offers offline access, so your most cherished moments are always just a tap away, even without an internet connection."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter_staggered_grid_view: 0.7.0
  
  flutter:
    sdk: flutter
  floor: ^1.4.2

  flutter_file_dialog: ^3.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  sqflite: ^2.3.2
  image_picker: ^1.0.7
  path_provider: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
